#!/bin/sh

cd /sidecar
for entry in $SIDECAR_SEEDS; do
	CLI="$CLI --cluster-ip $entry"
done

# If there's a BIND_IP and we don't already have it, add the
# address to the loopback interface.
if [[ -n "$BIND_IP" ]] && [[ $BIND_IP != "0.0.0.0" ]]; then
 	ip addr show | grep $BIND_IP
	if [[ $? -ne 0 ]]; then
		echo "Adding $BIND_IP to the loopback interface"
		ip addr add $BIND_IP/32 dev lo
	fi
fi

exec ./sidecar $CLI
