#!/bin/sh

cd /sidecar
for entry in $SIDECAR_SEEDS; do
	CLI="$CLI --cluster-ip $entry"
done

if [[ -n "$SIDECAR_DISCOVERY" ]]; then
	for entry in $SIDECAR_DISCOVERY; do
		CLI="$CLI --discover $entry"
	done
fi

BIND_IP=`grep bind_ip sidecar.toml | grep -o "[0-9]*\.[0-9]*\.[0-9]*\.[0-9]*"`

# If there's a BIND_IP and we don't already have it, add the
# address to the loopback interface.
if [[ -n "$BIND_IP" ]] && [[ $BIND_IP != "0.0.0.0" ]] && [[ ! ip addr show | grep $BIND_IP ]]; then
	echo "Adding $BIND_IP to the loopback interface"
	ip addr add $BIND_IP/32 dev lo
fi

exec ./sidecar $CLI
