#!/bin/sh

cd /sidecar

# As a transition from the old config, if there are spaces in
# the env var, add them as CLI options. Commas will be
# handled internally by envconfig.
echo $SIDECAR_SEEDS | grep ' ' >/dev/null
if [[ $? -eq 0 ]]; then
	cat <<EOF
	-------------------------------------------------------------------
		WARNING! Manually processing Sidecar seeds with spaces.
		THIS IS DEPRECATED AND WILL BE REMOVED. Use commas.
	-------------------------------------------------------------------
EOF
	for entry in $SIDECAR_SEEDS; do
		CLI="$CLI --cluster-ip $entry"
	done
fi

# If there's a BIND_IP and we don't already have it, add the
# address to the loopback interface.
if [[ -n "$BIND_IP" ]] && [[ $BIND_IP != "0.0.0.0" ]]; then
 	ip addr show | grep $BIND_IP
	if [[ $? -ne 0 ]]; then
		echo "Adding $BIND_IP to the loopback interface"
		ip addr add $BIND_IP/32 dev lo
	fi
fi

exec ./sidecar $CLI
